data:
  dataset_path: "data/ruwiki1b.arrow"
  train_size: 0.97
  val_size: 0.02
  mlm_probability: 0.15

model:
  emb_size: 312
  hidden_size: 312
  intermediate_size: 600
  max_position_embeddings: 512
  num_attention_heads: 12
  num_hidden_layers: 3

train:
  train_batch_size: 16
  gradient_accumulation_steps: 1
  lr:  0.001
  num_warmup_steps: 16384
  T_0: 32000
  b_1: 0.9
  b_2: 0.999
  epoches: 3
  weight_decay: 0.01
  log_interval: 512
  T: 5
  save_interval: 131072
  max_grad_norm: 1000
  val_interval: 32768

eval:
  val_batch_size: 16

tokenizer: "tokenizer/student_tokenizer_30021"

mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "Distillation_Experiment_New"
  run_name: "test"